import type { Metadata } from "next";
import { Jost } from "next/font/google";
import { type PropsWithChildren } from "react";

import { cn } from "@/lib/utils";
import { Providers } from "@/providers";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const font = Jost({ subsets: ["latin"] });

export default function Layout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={cn(font.className, "antialiased")}>
        <Providers className={font.className}>{children}</Providers>
      </body>
    </html>
  );
}
